import type { Metadata } from 'next'
import './globals.css'
import { GoogleTagManager } from '@next/third-parties/google'
import { Geist } from 'next/font/google'
import Script from 'next/script'
import { Footer } from '../components/Footer'
import { Header } from '../components/Header'
import { MainContainer } from '../components/Main'
import GlobalProviders from '../context/GlobalProviders'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <Script async src="/browserDetect/supportedBrowsers.js" />
      </head>
      {process.env.NEXT_GTM_ID && <GoogleTagManager gtmId={process.env.NEXT_GTM_ID} />}
      <body className={geistSans.variable}>
        <GlobalProviders>
          <Header />
          <MainContainer>{children}</MainContainer>
          <Footer />
        </GlobalProviders>
      </body>
    </html>
  )
}
