import type { Metadata } from 'next'
import './globals.css'
import { Geist } from 'next/font/google'
import GlobalProviders from '../context/GlobalProviders'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={geistSans.variable}>
        <GlobalProviders>
          {children}
        </GlobalProviders>
      </body>
    </html>
  )
}
